# Generated by Django 5.0.3 on 2026-05-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('actor_type', models.CharField(default='system', max_length=50)),
                ('actor_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type'], name='events_even_type_654a97_idx'), models.Index(fields=['entity_type', 'entity_id'], name='events_even_entity__109353_idx'), models.Index(fields=['created_at'], name='events_even_created_52c227_idx')],
            },
        ),
    ]
