# Generated by Django 5.0.3 on 2026-05-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trigger', models.CharField(db_index=True, max_length=100)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text="Filter conditions, e.g., {'new_status': 'cancelled'}")),
                ('actions', models.JSONField(default=list, help_text="List of actions: [{'type': 'send_telegram_message', 'message': '...'}]")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
